name: Build and Publish Docker Images for Other Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Compile microservices with Maven
      run: cd microservice-dapr-demo && mvn -B package 
    - name: Create Docker images 
      run: cd microservice-dapr-demo && sh ./docker-build.sh
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push images
      run: cd microservice-dapr-demo && sh ./docker-push.sh